steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/tejas-100947705/image:${COMMIT_SHA}', '.'
    ]
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/tejas-100947705/image:${COMMIT_SHA}']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
